---
- name: Remove old files
  command: sudo rm -rf /usr/share/nginx/html/nemm

- name: Setup application
  git: repo=https://github.com/tomaszsiemienik/nemm.git dest=/usr/share/nginx/html/nemm

- name: Install dependencies
  npm: path=/usr/share/nginx/html/nemm

- name: change chmod of project files
  file: 
    path: /usr/share/nginx/html/
    mode: 0777
    recurse: yes
